name: Build & Publish on Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        run: |
          scripts/deploy.sh \
            ${{ github.repository_owner }} \
            kippu-api \
            ${{ github.sha }}
